const CHANGE_FRAME_FONT = "CHANGE_FRAME_FONT"
const CHANGE_FRAME_SHAPE = "CHANGE_FRAME_SHAPE"
const ADD_NEW_FRAME = "ADD_NEW_FRAME"
const REMOVE_FRAME = "REMOVE_FRAME"
const OVER_FRAME = "OVER_FRAME"
const FRAME_HOLDERS = "FRAME_HOLDERS"
const FRAME_HOLDERS_TEMP = "FRAME_HOLDERS_TEMP"
const CHANGE_FRAME_TEXT = "CHANGE_FRAME_TEXT"
const CHANGE_FRAMES_SHAPE_TO_SHARP = "CHANGE_FRAMES_SHAPE_TO_SHARP"
const CHANGE_FRAMES_SHAPE_TO_ROUND = "CHANGE_FRAMES_SHAPE_TO_ROUND"
const OVER_FRAME_RE_RENDER = "OVER_FRAME_RE_RENDER"



const types = {
  CHANGE_FRAME_FONT,
  CHANGE_FRAME_SHAPE,
  ADD_NEW_FRAME,
  REMOVE_FRAME,
  OVER_FRAME,
  FRAME_HOLDERS,
  FRAME_HOLDERS_TEMP,
  CHANGE_FRAME_TEXT,
  CHANGE_FRAMES_SHAPE_TO_SHARP,
  CHANGE_FRAMES_SHAPE_TO_ROUND,
  OVER_FRAME_RE_RENDER
}

export default types