const CHANGE_FRAME_FONT = "CHANGE_FRAME_FONT"
const CHANGE_FRAME_SHAPE = "CHANGE_FRAME_SHAPE"
const ADD_NEW_FRAME = "ADD_NEW_FRAME"
const ADD_NEW_FRAME_FLAG = "ADD_NEW_FRAME_FLAG"
const REMOVE_FRAME = "REMOVE_FRAME"
const REMOVE_FRAME_LIST = "REMOVE_FRAME_LIST"
const OVER_FRAME = "OVER_FRAME"
const FRAME_LIST = "FRAME_LIST"
const FRAME_HOLDERS = "FRAME_HOLDERS"
const FRAME_HOLDERS_TEMP = "FRAME_HOLDERS_TEMP"



const types = {
  CHANGE_FRAME_FONT,
  CHANGE_FRAME_SHAPE,
  ADD_NEW_FRAME,
  ADD_NEW_FRAME_FLAG,
  REMOVE_FRAME,
  REMOVE_FRAME_LIST,
  OVER_FRAME,
  FRAME_LIST,
  FRAME_HOLDERS,
  FRAME_HOLDERS_TEMP,
}

export default types