const CHANGE_COLOR = "CHANGE_COLOR"
const SET_FRONT_END_REDUCER_COLOR = "SET_FRONT_END_REDUCER_COLOR"
const RESET_COLOR = "RESET_COLOR"

const types = {
  CHANGE_COLOR,
  SET_FRONT_END_REDUCER_COLOR,
  RESET_COLOR
}
export default types