const CHANGE_TEXT_FONT = "CHANGE_TEXT_FONT"
const TEXT_RE_RENDER = "TEXT_RE_RENDER"
const SET_FRONT_END_REDUCER_TEXT = "SET_FRONT_END_REDUCER_TEXT"

const types = {
  CHANGE_TEXT_FONT,
  TEXT_RE_RENDER,
  SET_FRONT_END_REDUCER_TEXT
}

export default types