const ADD_PANEL = "ADD_PANEL"
const UPDATE_PANELS = "UPDATE_PANELS"
const SHOW_DASHBOARD = "SHOW_DASHBOARD"
const CHANGE_INDEX_OF_LAST_PANEL = "CHANGE_INDEX_OF_LAST_PANEL"



const types = {
  ADD_PANEL,
  UPDATE_PANELS,
  SHOW_DASHBOARD,
  CHANGE_INDEX_OF_LAST_PANEL
}
export default types