const CHANGE_PANEL_NAME = "CHANGE_PANEL_NAME"
const CHANGE_PANEL_TYPE = "CHANGE_PANEL_TYPE"
const CHANGE_PANEL_COLOR = "CHANGE_PANEL_COLOR"
const RESET_PANEL_COLOR = "RESET_PANEL_COLOR"
const CHANGE_PANEL_TEXT = "CHANGE_PANEL_TEXT"
const CHANGE_FRAMES = "CHANGE_FRAMES"
const CHANGE_ICONS = "CHANGE_ICONS"
const SET_BACK_END_REDUCER = "CHANGE_SET_BACK_END_REDUCERICONS"


const types = {
  CHANGE_PANEL_NAME,
  CHANGE_PANEL_TYPE,
  CHANGE_PANEL_COLOR,
  RESET_PANEL_COLOR,
  CHANGE_PANEL_TEXT,
  CHANGE_FRAMES,
  CHANGE_ICONS,
  SET_BACK_END_REDUCER
}
export default types