// eslint-disable-next-line 
const availablePanels = [
  {
    type: "MDOT_2",
    name: "mdot_2",
    numberOfDots: 2,
    panelRotation: 0,
    height: 90,
    width: 90,
    lcdScreen: false,
    rows: [1, 1, 1],
    dotLocation: [0, 0, 0,
      1, 0, 1,
      0, 0, 0],
    marginTop: 10.6,
    marginBottom: 9.8,
    marginSide: 9.8,
    sideCellWidth: 22.4,
    centerCellWidth: 25.6,
    rowHeight: 24,
    lastRowHeight: 21.6,
    oneRowFrameHeight: 19.5,
    multiRowFrameHeight: 24,
    marginFrameTop: 11,
    marginFrameBottom: 11.5,
    sideColumnFrameWidth: 21.06,
    centerColumnFrameWidth: 27.28,
    marginFrameSide: 10.3,
    backEndPanelType: 0,
    picture: (require("../../../../assets/panelpictures/mdot2v.jpg")).default,
    info: "MDOT_2_INFO",
    link: "MDOT_2_LINK",
  },
  {
    type: "MDOT_4",
    name: "mdot_4",
    numberOfDots: 4,
    panelRotation: 0,
    height: 90,
    width: 90,
    lcdScreen: false,
    rows: [1, 1, 1],
    dotLocation: [1, 0, 1,
      0, 0, 0,
      1, 0, 1],
    marginTop: 10.6,
    marginBottom: 9.8,
    marginSide: 9.8,
    sideCellWidth: 22.4,
    centerCellWidth: 25.6,
    rowHeight: 24,
    lastRowHeight: 21.6,
    oneRowFrameHeight: 19.5,
    multiRowFrameHeight: 24,
    marginFrameTop: 11,
    marginFrameBottom: 11.5,
    sideColumnFrameWidth: 21.06,
    centerColumnFrameWidth: 27.28,
    marginFrameSide: 10.3,
    backEndPanelType: 1,
    picture: (require("../../../../assets/panelpictures/mdot4v.jpg")).default,
    info: "MDOT_4_INFO",
    link: "MDOT_4_LINK",
  },
  // {
  //   type: "MDOT_6",// stary
  //   name: "mdot_6",
  //   numberOfDots: 6,
  //   panelRotation: 0,
  //   height: 90,
  //   width: 90,
  //   lcdScreen: {
  //     lcdType: "noslide",
  //     lcdHeight: 37,
  //     lcdWidth: 30,
  //     lcdTop: 25,
  //     lcdLeft: 30,
  //   },
  //   rows: [1, 1, 1],
  //   dotLocation: [1, 0, 1,
  //     1, 0, 1,
  //     1, 0, 1],
  //   marginTop: 9.8,
  //   marginBottom: 9.8,
  //   marginSide: 9.8,
  //   sideCellWidth: 22.4,
  //   centerCellWidth: 25.6,
  //   rowHeight: 24,
  //   lastRowHeight: 22.4,
  //   oneRowFrameHeight: 19.5,
  //   multiRowFrameHeight: 24,
  //   marginFrameTop: 10,
  //   marginFrameBottom: 12.5,
  //   sideColumnFrameWidth: 21.06,
  //   centerColumnFrameWidth: 27.28,
  //   marginFrameSide: 10.3,
  //   backEndPanelType: 2,
  //   picture: (require("../../../../assets/panelpictures/mdot6v.jpg")).default,
  //   info: "MDOT_6_INFO",
  //   link: "MDOT_6_LINK",
  // },
  {
    type: "MDOT_6",
    name: "mdot_6",
    numberOfDots: 6,
    panelRotation: 0,
    height: 90,
    width: 90,
    lcdScreen: {
      lcdType: "noslide",
      lcdHeight: 42.2,
      lcdWidth: 31.8,
      lcdTop: 22.15,
      lcdLeft: 29.1,
    },
    rows: [1, 1, 1],
    dotLocation: [1, 0, 1,
      1, 0, 1,
      1, 0, 1],
    marginTop: 9,
    marginBottom: 9.8,
    marginSide: 9.8,
    sideCellWidth: 22.4,
    centerCellWidth: 25.6,
    rowHeight: 24,
    lastRowHeight: 23.2,
    oneRowFrameHeight: 19.5,
    multiRowFrameHeight: 24,
    marginFrameTop: 9.4,
    marginFrameBottom: 13.1,
    sideColumnFrameWidth: 21.06,
    centerColumnFrameWidth: 27.28,
    marginFrameSide: 10.3,
    backEndPanelType: 3,
    picture: (require("../../../../assets/panelpictures/mdot6newv.jpg")).default,
    info: "MDOT_6_INFO",
    link: "MDOT_6_LINK",
  },
  {
    type: "MDOT_9",
    name: "mdot_9",
    numberOfDots: 9,
    panelRotation: 0,
    height: 90,
    width: 90,
    lcdScreen: false,
    rows: [1, 1, 1],
    dotLocation: [1, 1, 1,
      1, 1, 1,
      1, 1, 1],
    marginTop: 10.6,
    marginBottom: 9.8,
    marginSide: 9.8,
    sideCellWidth: 22.4,
    centerCellWidth: 25.6,
    rowHeight: 24,
    lastRowHeight: 21.6,
    oneRowFrameHeight: 19.5,
    multiRowFrameHeight: 24,
    marginFrameTop: 11,
    marginFrameBottom: 11.5,
    sideColumnFrameWidth: 21.06,
    centerColumnFrameWidth: 27.28,
    marginFrameSide: 10.3,
    backEndPanelType: 4,
    picture: (require("../../../../assets/panelpictures/mdot9v.jpg")).default,
    info: "MDOT_9_INFO",
    link: "MDOT_9_LINK",
  },
  // {
  //   type: "MDOT_15",
  //   name: "mdot_15",
  //   numberOfDots: 15,
  //   panelRotation: 0,
  //   height: 160,
  //   width: 90,
  //   lcdScreen: {
  //     lcdType: "noslide",
  //     lcdHeight: 37,
  //     lcdWidth: 30,
  //     lcdTop: 25,
  //     lcdLeft: 30,
  //   },
  //   rows: [1, 1, 1, 1, 1, 1],
  //   dotLocation: [1, 0, 1,
  //     1, 0, 1,
  //     1, 0, 1,
  //     1, 1, 1,
  //     1, 1, 1,
  //     1, 1, 1],
  //   marginTop: 9.6,
  //   marginBottom: 9.6,
  //   marginSide: 9.8,
  //   sideCellWidth: 22.4,
  //   centerCellWidth: 25.6,
  //   rowHeight: 24,
  //   lastRowHeight: 20.8,
  //   oneRowFrameHeight: 19.5,
  //   multiRowFrameHeight: 24,
  //   marginFrameTop: 10,
  //   marginFrameBottom: 10.5,
  //   sideColumnFrameWidth: 21.06,
  //   centerColumnFrameWidth: 27.28,
  //   marginFrameSide: 10.3,
  //   backEndPanelType: 5,
  //   picture: (require("../../../../assets/panelpictures/mdot15v.jpg")).default,
  //   info: "MDOT_15_INFO" ,
  //   link: "MDOT_15_LINK"
  // },
  {
    type: "MDOT_18",
    name: "mdot_18",
    numberOfDots: 18,
    panelRotation: 0,
    height: 160,
    width: 90,
    lcdScreen: false,
    rows: [1, 1, 1, 1, 1, 1],
    dotLocation: [1, 1, 1,
      1, 1, 1,
      1, 1, 1,
      1, 1, 1,
      1, 1, 1,
      1, 1, 1],
    marginTop: 9.6,
    marginBottom: 9.6,
    marginSide: 9.8,
    sideCellWidth: 22.4,
    centerCellWidth: 25.6,
    rowHeight: 24,
    lastRowHeight: 20.8,
    oneRowFrameHeight: 19.5,
    multiRowFrameHeight: 24,
    marginFrameTop: 10,
    marginFrameBottom: 10.5,
    sideColumnFrameWidth: 21.06,
    centerColumnFrameWidth: 27.28,
    marginFrameSide: 10.3,
    backEndPanelType: 6,
    picture: (require("../../../../assets/panelpictures/mdot18v.jpg")).default,
    info: "MDOT_18_INFO",
    link: "MDOT_18_LINK",
  },
  {
    type: "MDOT_18_HORIZONTAL",
    name: "mdot_18_horizontal",
    numberOfDots: 18,
    panelRotation: 90,
    height: 160,
    width: 90,
    lcdScreen: false,
    rows: [1, 1, 1, 1, 1, 1],
    dotLocation: [1, 1, 1,
      1, 1, 1,
      1, 1, 1,
      1, 1, 1,
      1, 1, 1,
      1, 1, 1],
    marginTop: 9.6,
    marginBottom: 9.6,
    marginSide: 9.8,
    sideCellWidth: 22.4,
    centerCellWidth: 25.6,
    rowHeight: 24,
    lastRowHeight: 20.8,
    oneRowFrameHeight: 19.5,
    multiRowFrameHeight: 24,
    marginFrameTop: 10,
    marginFrameBottom: 10.5,
    sideColumnFrameWidth: 21.06,
    centerColumnFrameWidth: 27.28,
    marginFrameSide: 10.3,
    backEndPanelType: 7,
    picture: (require("../../../../assets/panelpictures/mdot18pozv.jpg")).default,
    info: "MDOT_18_INFO",
    link: "MDOT_18_LINK",
  },
  {
    type: "MDOT_M18",
    name: "mdot_m18",
    numberOfDots: 18,
    panelRotation: 0,
    height: 160,
    width: 90,
    lcdScreen: {
      lcdType: "noslide",
      lcdHeight: 42.2,
      lcdWidth: 31.8,
      lcdTop: 18.9,
      lcdLeft: 29.1,
    },
    rows: [1, 1, 1, 1, 1, 1, 1],
    dotLocation: [1, 0, 1,
      1, 0, 1,
      1, 0, 1,
      1, 1, 1,
      1, 1, 1,
      1, 1, 1,
      1, 1, 1],
    marginTop: 9.6,
    marginBottom: 9.6,
    marginSide: 9.8,
    sideCellWidth: 22.4,
    centerCellWidth: 25.6,
    rowHeight: 20,
    lastRowHeight: 20.8,
    oneRowFrameHeight: 19.5,
    multiRowFrameHeight: 20,
    marginFrameTop: 10,
    marginFrameBottom: 10.5,
    sideColumnFrameWidth: 21.06,
    centerColumnFrameWidth: 27.28,
    marginFrameSide: 10.3,
    backEndPanelType: 8,
    picture: (require("../../../../assets/panelpictures/mdotm18v.jpg")).default,
    info: "MDOT_M18_INFO",
    link: "MDOT_M18_LINK",
  },
  {
    type: "MDOT_M18_UNIVERSAL",
    name: "mdot_m18_universal",
    numberOfDots: 18,
    panelRotation: 0,
    height: 160,
    width: 90,
    lcdScreen: {
      lcdType: "slide",
      lcdHeight: 42.2,
      lcdWidth: 31.8,
      lcdTop: 18.9,
      lcdLeft: 29.1,
    },
    rows: [1, 1, 1, 1, 1, 1, 1],
    dotLocation: [0, 0, 0,
      0, 0, 0,
      0, 0, 0,
      1, 1, 1,
      1, 1, 1,
      1, 1, 1,
      1, 1, 1],
    marginTop: 9.6,
    marginBottom: 9.6,
    marginSide: 9.8,
    sideCellWidth: 22.4,
    centerCellWidth: 25.6,
    rowHeight: 20,
    lastRowHeight: 20.8,
    oneRowFrameHeight: 19.5,
    multiRowFrameHeight: 20,
    marginFrameTop: 10,
    marginFrameBottom: 10.5,
    sideColumnFrameWidth: 21.06,
    centerColumnFrameWidth: 27.28,
    marginFrameSide: 10.3,
    backEndPanelType: 9,
    picture: (require("../../../../assets/panelpictures/mdotm18univ.jpg")).default,
    info: "MDOT_M18_UNIVERSAL_INFO",
    link: "MDOT_M18_UNIVERSAL_LINK",
  },
];

export default availablePanels