const CHANGE_ICON_HOLDERS = "CHANGE_ICON_HOLDERS"
const ADD_ICON_TO_FAVORITE = "ADD_ICON_TO_FAVORITE"
const REMOVE_ICON_FROM_FAVORITE = "REMOVE_ICON_FROM_FAVORITE"
const IS_ANY_SELECTED = "IS_ANY_SELECTED"
const SET_FRONT_END_REDUCER_ICON = "SET_FRONT_END_REDUCER_ICON"



const types = {
  CHANGE_ICON_HOLDERS,
  ADD_ICON_TO_FAVORITE,
  REMOVE_ICON_FROM_FAVORITE,
  IS_ANY_SELECTED,
  SET_FRONT_END_REDUCER_ICON
}

export default types