const TOGGLE_VISUAL = "TOGGLE_VISUAL"
const CHANGE_SCALE = "CHANGE_SCALE"
const TOGGLE_ANIMATIONS = "TOGGLE_ANIMATIONS"
const SHOW_REMOVE_ICON = "SHOW_REMOVE_ICON"
const SHOW_REMOVE_ICONS = "SHOW_REMOVE_ICONS"
const CHANGE_PANEL_NAME = "CHANGE_PANEL_NAME"
const SET_TIME_OF_CREATION = "SET_TIME_OF_CREATION"
const SET_FRONT_END_REDUCER_VISUAL = "SET_FRONT_END_REDUCER_VISUAL"


const types = {
  TOGGLE_VISUAL,
  CHANGE_SCALE,
  TOGGLE_ANIMATIONS,
  SHOW_REMOVE_ICON,
  SHOW_REMOVE_ICONS,
  CHANGE_PANEL_NAME,
  SET_TIME_OF_CREATION,
  SET_FRONT_END_REDUCER_VISUAL
}
export default types