const CHANGE_MODEL = "CHANGE_MODEL"
const RESET_MODEL = "RESET_MODEL"
const RESET_ALL_AFTER_MODEL_CHANGE = "RESET_ALL_AFTER_MODEL_CHANGE"

const types = {
  CHANGE_MODEL,
  RESET_MODEL,
  RESET_ALL_AFTER_MODEL_CHANGE
}
export default types