const CHANGE_ICON_HOLDERS = "CHANGE_ICON_HOLDERS"
const ADD_ICON_TO_FAVORITE = "ADD_ICON_TO_FAVORITE"
const REMOVE_ICON_FROM_FAVORITE = "REMOVE_ICON_FROM_FAVORITE"



const types = {
  CHANGE_ICON_HOLDERS,
  ADD_ICON_TO_FAVORITE,
  REMOVE_ICON_FROM_FAVORITE
}

export default types